### ISSUE TITLE
Only 5 data points on graph

### ISSUE THREAD

**Issue by dpavlin** [swharden/diyECG-1opAmp#1]
First, let me say thanks for this very interesting project.

I just made it and it seems to work, however, I'm getting just 5 data points on graph as you can see on http://mjesec.ffzg.hr/~dpavlin/tmp/ECG_1470671653.png

My opamp is LM358, and while it's spec is not same as LM741, they seem close enough.

I'm python newbie, so any help in resolving this would be appreciated.

**Comment by swharden** [comment]
Could it be recorded something other than your microphone? Glance at your primary sound input devices and ensure that the correct microphone is being recorded.

**Comment by swharden** [comment]
Alternatively, it could be a float/integer issue. In go.py, change the part:

`self.grECG.plot(np.arange(len(data))/self.ear.rate,`...
to 
`self.grECG.plot(np.arange(len(data))/float(self.ear.rate),`...

Does that fix it?

**Comment by swharden** [comment]
Make sure your microphone device is what you want it to be.
It's programmed to use the system's default input device.
It says the name of the device it's using in gray just below the title.
![screenshot](http://swharden.com/tmp/pub/ecgSndDev.jpg)

**Comment by swharden** [comment]
Alternatively, the issue could be a weird versioning issue (perhaps with numpy). If you're on Windows, try using the WinPython distribution I mention in the readme. It _should_ work fine with that distribution right out of the box

**Comment by dpavlin** [comment]
Thanks for help. It seems that you deleted one comment which fixed my problem, adding float to following line:

`self.grECG.plot(np.arange(len(data))/float(self.ear.rate),data,clear=True`

I'm running this under Debian Linux, so my assuption is that all versions are in sync, and indeed it does work now.

**Comment by swharden** [comment]
I second guessed myself and thought surely that wouldn't be the problem, hence removing my own comment which turned out to be true. I'm glad it's working! I'll commit that change to the code now. It probably is a python versioning thing. Thanks so much for the message!

**Comment by swharden** [comment]
... care to post a screenshot of your working output?
