### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by S-Aries** [swharden/diyECG-1opAmp#3]
Hi, 
I really want to get this working but every time I click the batch file I get an error.
![python not working](https://cloud.githubusercontent.com/assets/22327183/18680624/32668a82-7f2a-11e6-8c66-9dd463b710c7.PNG)

I have windows 10, I downloaded the recommended version of winpython, and renamed the go.bat file exactly as in your video.
I have no idea of what to do or what is going on but I have no experience with python and could really use help. 
I did notice that none of my pthyon applications have ".exe" next to them, but they still run when I click on them.
Thank you.

**Comment by swharden** [comment]
Hi Scot-Alan,

I think this problem is a problem with Python as it is configured on your computer. I found [this StackOverflow post](http://stackoverflow.com/questions/6320529/pyqt-import-error) and [this google group page](https://groups.google.com/forum/#!topic/winpython/fIo5uJpwQKE) describing others who have had the same issue. The problem seems to be resolved by completely uninstalling Python 2.x from your system, and ensuring you have the correct version of Python 3.x installed (64 bit or 32 bit). With Python 2 removed, I suspect the code will work again!

**Comment by S-Aries** [comment]
Hi Scott,

Thank you for getting back to me. I read the link and while that is the
exact error that I am getting I can't find a python 2.x on my system.
However, I did get it to work. I opened winpython command prompt and
navigated to the "diyECG" folder using the "cd" and "dir" commands. Once in
the software folder I typed "go.bat.bat" and it ran, I have used it
multiple times and this is the only method that will make it run. I dont
mind so as long as it works, witch it does. :D
I just thought I would let you know.
Thank you again for responding so quickly.

Scot-Alan Hedrick
P.s is the single opAmp version of this device better than the one you made
using a complete lm324. I was just wondering because I have an oscilloscope
and would not mind a cool project for it.
Thanks again.

**Comment by swharden** [comment]
Excellent! I guess if others have similar issues I will encourage them to open up "WinPython Command Prompt.exe" (in the WinPython folder), use `cd` commands to navigate to where `go.py` exists, and run the command `python go.py` (which would do the same that running go.bat does). Thanks for the update!

For an improved circuit to interface directly to an oscilloscope (and therefore not allow any software "smoothing" of the signal), consider using an instrumentation amplifier line an AD620. The [datasheet for the AD620](http://www.analog.com/media/en/technical-documentation/data-sheets/AD620.pdf) even has a circuit diagram to make an ECG. The downside is the relatively high cost of that chip.
