### ISSUE TITLE
'Electrodes' won't detect anything.

### ISSUE THREAD

**Issue by MayNavarro** [swharden/diyECG-1opAmp#5]
Hello Scott, 
first of all your ECG work is amazing!! I'm currently studying electromedicine and I always wanted to make a simple electrocardiograph with not such expensive components, and you already did it! 
I tried to follow all the steps to make it work but when I connect it to the computer, I don't get the ECG wave like yours. I am obviously doing something wrong but I dont know what it is.
I changed the path of the python.exe and made it run but, when it comes to the circuit I probably did something wrong.  Here's a picture of how I made it.

![WhatsApp Image 2021-06-14 at 11 29 35](https://user-images.githubusercontent.com/85872205/121871001-e4abea80-cd03-11eb-9781-4e20a1bd1a15.jpeg)

**Comment by swharden** [comment]
Hi @MayNavarro,

I agree there is probably a problem with your circuit. On pin 7 (+) there is a resistor to ground which does not make sense. Refer to the schematic and build the circuit carefully, ensuring each connection is accurate.

Good luck!
Scott
