### ISSUE TITLE
where can I find demo_ecg.wav

### ISSUE THREAD

**Issue by johncohnvt** [swharden/diyECG-1opAmp#6]
Scott.. I'm enjoying playing with your diyECG project.. I'm doing some experimentation with high frequency QRS waves in an ECG and your circuit and sw are a great starting point !. I've proted the SW to use Qt5 on a Mac and its working well. I noticed you mention  a .wav sample demo_ecg.wav   .. I can't find it. Any chance you could post it or send it to me at johncohnvt@gmail.com

Thanks for this great project !
John cohn

**Comment by swharden** [comment]
Hi @johncohnvt, 

I updated this repository to include a new section containing sample data and demonstrating how to analyze it with Python. It's not exactly `demo_ecg.wav` but it's a very similar file (recorded as a 1kHz WAV file directly from the op-amp).

https://github.com/swharden/diyECG-1opAmp#python-analysis

![image](https://user-images.githubusercontent.com/4165489/146686472-4caa7328-3990-4cef-b066-86e36e322d7a.png)

https://github.com/swharden/diyECG-1opAmp/blob/321f00158d4f9669df841434c1a2d46d71e3b77e/data/analyze.py#L1-L50

**Comment by johncohnvt** [comment]
Scott,
One quick signal processing question… Your example using just the FFT/IFFT for such an easy and elegant way to do high pass low pass band pass , notch etc.… What are the pros and cons of using that Simple sort of filtering for  ekg Versus using the more sophisticated filtering in scipy  and other packages?

Sorry for all the questions… But I feel very lucky to a found someone thinking about the same problems that I am.
happy holidays!
-jc


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by swharden** [comment]
Hi @johncohnvt 

I actually think doing the FFT/iFFT should do about the same thing in C# as with Python and SciPy. There are some very slight differences between different types of stop/pass filters, but practically the small differences are unlikely to affect this project.

I'd summarize that filters that use FFT/iFFT require a computer to do filtering, but different types of filters (e.g., Bessel) can be built with simple hardware components like inductors and capacitors, so they're useful for building hardware circuits.

I searched YouTube for this topic and found a surprisingly relevant video on this exact topic! 
https://youtu.be/q8AfH4_n61o

Hope it helps!
Scott
